# -*- coding: utf-8 -*-
"""app_BMV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hbWRIeQh7sfOV5Pt5hNWRT10AJOT9b1k
"""

import streamlit as st
import pandas as pd
import csv
from tradingview_ta import TA_Handler, Interval

# ---------------------------------------
#  Diccionario de acciones (tu lista)
# ---------------------------------------
acciones = {
    'AC': {'screener': 'mexico', 'exchange': 'BMV'},
    'ACCELSA/B': {'screener': 'mexico', 'exchange': 'BMV'},
    'ACTINVR/B': {'screener': 'mexico', 'exchange': 'BMV'},
    'AGUA': {'screener': 'mexico', 'exchange': 'BMV'},
    'ALFA/A': {'screener': 'mexico', 'exchange': 'BMV'},
    'ALPEK/A': {'screener': 'mexico', 'exchange': 'BMV'},
    'ALSEA': {'screener': 'mexico', 'exchange': 'BMV'},
    'AMX/B': {'screener': 'mexico', 'exchange': 'BMV'},
    'ASUR/B': {'screener': 'mexico', 'exchange': 'BMV'},
    'AUTLAN/B': {'screener': 'mexico', 'exchange': 'BMV'},
    'AXTEL/CPO': {'screener': 'mexico', 'exchange': 'BMV'},
    'BBAJIO/O': {'screener': 'mexico', 'exchange': 'BMV'},
    'BEVIDES/A': {'screener': 'mexico', 'exchange': 'BMV'},
    'BIMBO/A': {'screener': 'mexico', 'exchange': 'BMV'},
    'BOLSA/A': {'screener': 'mexico', 'exchange': 'BMV'},
    'CABLE/CPO': {'screener': 'mexico', 'exchange': 'BMV'},
    'CADU/A': {'screener': 'mexico', 'exchange': 'BMV'},
    'CHDRAUI/B': {'screener': 'mexico', 'exchange': 'BMV'},
    'CIDMEGA': {'screener': 'mexico', 'exchange': 'BMV'},
    'CIE/B': {'screener': 'mexico', 'exchange': 'BMV'},
    'CMOCTEZ': {'screener': 'mexico', 'exchange': 'BMV'},
    'CMR/B': {'screener': 'mexico', 'exchange': 'BMV'},
    'CONVER/A': {'screener': 'mexico', 'exchange': 'BMV'},
    'CREAL': {'screener': 'mexico', 'exchange': 'BMV'},
    'CTAXTEL/A': {'screener': 'mexico', 'exchange': 'BMV'},
    'CUERVO': {'screener': 'mexico', 'exchange': 'BMV'},
    'CULTIBA/B': {'screener': 'mexico', 'exchange': 'BMV'},
    'CYDSASA/A': {'screener': 'mexico', 'exchange': 'BMV'},
    'DINE/A': {'screener': 'mexico', 'exchange': 'BMV'},
    'FEMSA/UB': {'screener': 'mexico', 'exchange': 'BMV'},
    'FINAMEX/O': {'screener': 'mexico', 'exchange': 'BMV'},
    'FINDEP': {'screener': 'mexico', 'exchange': 'BMV'},
    'FRAGUA/B': {'screener': 'mexico', 'exchange': 'BMV'},
    'GAP/B': {'screener': 'mexico', 'exchange': 'BMV'},
    'GBM/O': {'screener': 'mexico', 'exchange': 'BMV'},
    'GCARSO/A1': {'screener': 'mexico', 'exchange': 'BMV'},
    'GCC': {'screener': 'mexico', 'exchange': 'BMV'},
    'GENTERA': {'screener': 'mexico', 'exchange': 'BMV'},
    'GFINBUR/O': {'screener': 'mexico', 'exchange': 'BMV'},
    'GFNORTE/O': {'screener': 'mexico', 'exchange': 'BMV'},
    'GIGANTE': {'screener': 'mexico', 'exchange': 'BMV'},
    'GISSA/A': {'screener': 'mexico', 'exchange': 'BMV'},
    'GMD': {'screener': 'mexico', 'exchange': 'BMV'},
    'GMEXICO/B': {'screener': 'mexico', 'exchange': 'BMV'},
    'GMXT': {'screener': 'mexico', 'exchange': 'BMV'},
    'GNP': {'screener': 'mexico', 'exchange': 'BMV'},
    'GPROFUT': {'screener': 'mexico', 'exchange': 'BMV'},
    'GRUMA/B': {'screener': 'mexico', 'exchange': 'BMV'},
    'HCITY': {'screener': 'mexico', 'exchange': 'BMV'},
    'HERDEZ': {'screener': 'mexico', 'exchange': 'BMV'},
    'HOMEX': {'screener': 'mexico', 'exchange': 'BMV'},
    'HOTEL': {'screener': 'mexico', 'exchange': 'BMV'},
    'ICH/B': {'screener': 'mexico', 'exchange': 'BMV'},
    'INVEX/A': {'screener': 'mexico', 'exchange': 'BMV'},
    'KIMBER/A': {'screener': 'mexico', 'exchange': 'BMV'},
    'KOF/UBL': {'screener': 'mexico', 'exchange': 'BMV'},
    'KUO/A': {'screener': 'mexico', 'exchange': 'BMV'},
    'LAB/B': {'screener': 'mexico', 'exchange': 'BMV'},
    'LAMOSA': {'screener': 'mexico', 'exchange': 'BMV'},
    'LIVEPOL/1': {'screener': 'mexico', 'exchange': 'BMV'},
    'MEDICA/B': {'screener': 'mexico', 'exchange': 'BMV'},
    'MEGA/CPO': {'screener': 'mexico', 'exchange': 'BMV'},
    'MFRISCO/A-1': {'screener': 'mexico', 'exchange': 'BMV'},
    'MINSA/B': {'screener': 'mexico', 'exchange': 'BMV'},
    'NEMAK/A': {'screener': 'mexico', 'exchange': 'BMV'},
    'OMA/B': {'screener': 'mexico', 'exchange': 'BMV'},
    'ORBIA': {'screener': 'mexico', 'exchange': 'BMV'},
    'PASA/B': {'screener': 'mexico', 'exchange': 'BMV'},
    'PE_OLES': {'screener': 'mexico', 'exchange': 'BMV'},
    'PINFRA': {'screener': 'mexico', 'exchange': 'BMV'},
    'POCHTEC/B': {'screener': 'mexico', 'exchange': 'BMV'},
    'POSADAS/A': {'screener': 'mexico', 'exchange': 'BMV'},
    'Q': {'screener': 'mexico', 'exchange': 'BMV'},
    'R/A': {'screener': 'mexico', 'exchange': 'BMV'},
    'RLH/A': {'screener': 'mexico', 'exchange': 'BMV'},
    'SIMEC/B': {'screener': 'mexico', 'exchange': 'BMV'},
    'SITES1/A-1': {'screener': 'mexico', 'exchange': 'BMV'},
    'SORIANA/B': {'screener': 'mexico', 'exchange': 'BMV'},
    'SPORT/S': {'screener': 'mexico', 'exchange': 'BMV'},
    'TEAK/CPO': {'screener': 'mexico', 'exchange': 'BMV'},
    'TMM/A': {'screener': 'mexico', 'exchange': 'BMV'},
    'TRAXION/A': {'screener': 'mexico', 'exchange': 'BMV'},
    'VASCONI': {'screener': 'mexico', 'exchange': 'BMV'},
    'VESTA': {'screener': 'mexico', 'exchange': 'BMV'},
    'VINTE': {'screener': 'mexico', 'exchange': 'BMV'},
    'VISTA/A': {'screener': 'mexico', 'exchange': 'BMV'},
    'VITRO/A': {'screener': 'mexico', 'exchange': 'BMV'},
    'VOLAR/A': {'screener': 'mexico', 'exchange': 'BMV'},
    'WALMEX': {'screener': 'mexico', 'exchange': 'BMV'},
    'FMTY/14': {'screener': 'mexico', 'exchange': 'BMV'},
    'ACWI': {'screener': 'mexico', 'exchange': 'BMV'},
    'IAU': {'screener': 'mexico', 'exchange': 'BMV'},
}

# ---------------------------------------------------------------------------------
# STREAMLIT APP
# ---------------------------------------------------------------------------------

st.title("*El Mercado es Tuyo* — Análisis Técnico Automático")

st.write("Analiza automáticamente todas las emisoras listadas en México.")

# Botón para ejecutar análisis
if st.button("Ejecutar Análisis Técnico del Mercado"):
    resultados = []

    with st.spinner("Analizando acciones… puede tardar unos segundos,mientras tómate un cafecito.  "):
        for symbol, config in acciones.items():
            try:
                handler = TA_Handler(
                    symbol=symbol,
                    screener=config['screener'],
                    exchange=config['exchange'],
                    interval=Interval.INTERVAL_1_WEEK
                )

                analysis = handler.get_analysis()

                resultados.append({
                    'Símbolo': symbol,
                    'Tendencia': analysis.summary["RECOMMENDATION"],
                    'Indicadores': str(analysis.indicators)
                })
            except Exception as e:
                resultados.append({
                    'Símbolo': symbol,
                    'Tendencia': "ERROR",
                    'Indicadores': str(e)
                })

    df_resultados = pd.DataFrame(resultados)

    st.success("✔ Análisis completado")

    # Mostrar datos
    st.dataframe(df_resultados)

    # Descargar CSV
    csv_data = df_resultados.to_csv(index=False, quoting=csv.QUOTE_NONNUMERIC)
    st.download_button(
        label="Descargar CSV",
        data=csv_data,
        file_name="El_mercado_es_tuyo.csv",
        mime="text/csv"
    )

else:
    st.info("Haz clic en el botón para analizar las acciones.")

# Personalización de diseño
st.markdown("""
<style>
    .stApp {
        background-color:  #F2B6C0;
    }
    .css-1d391kg {
        color:  #000000;
    }
</style>
""", unsafe_allow_html=True)

# -----------------------------------------------------
